2087512 integrate bootstrap
jlandwehr-avarteq/Avarteq-Recipes pull request #3
Opened 2016-10-06 11:28 UTC by jlandwehr-avarteq

The Bootstrap Framework was integrated into the project.

@arkanoryn

2016-10-07 11:21 UTC, arkanoryn commented
Where is the integration?

You didn't updated the `layout/app.html...`

2016-10-07 11:29 UTC, arkanoryn requested changes

2016-10-07 11:29 UTC, arkanoryn commented on Gemfile
> +gem 'sass-rails', '>= 3.2'
can you not use sass 5.0?

2016-10-10 07:47 UTC, jlandwehr-avarteq commented
Merge done

2016-10-10 07:47 UTC, closed without merging